import {
  siApachemaven,
  siAstro,
  siCloudflare,
  siCloudflarepages,
  siCss,
  siDocker,
  siFigma,
  siGit,
  siGithub,
  siHtml5,
  siJavascript,
  siLua,
  siNetlify,
  siNextdotjs,
  siNodedotjs,
  siOpenjdk,
  siReact,
  siSpringboot,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siVite,
  siVitest,
  type SimpleIcon,
} from "simple-icons";

// Logos de Simple Icons (CC0). Se dibujan en un solo tono con currentColor, nunca con el color de la marca.
export const logos = {
  apachemaven: siApachemaven,
  astro: siAstro,
  cloudflare: siCloudflare,
  cloudflarepages: siCloudflarepages,
  css: siCss,
  docker: siDocker,
  figma: siFigma,
  git: siGit,
  github: siGithub,
  html5: siHtml5,
  javascript: siJavascript,
  lua: siLua,
  netlify: siNetlify,
  nextdotjs: siNextdotjs,
  nodedotjs: siNodedotjs,
  openjdk: siOpenjdk,
  react: siReact,
  springboot: siSpringboot,
  supabase: siSupabase,
  tailwindcss: siTailwindcss,
  typescript: siTypescript,
  vite: siVite,
  vitest: siVitest,
} satisfies Record<string, SimpleIcon>;

export type Logo = keyof typeof logos;
